load("@npm_bazel_typescript//:index.bzl", "ts_library")

ts_library(
    name = "logger",
    srcs = ["index.ts"],
    visibility = ["//visibility:public"],
    deps = [
        "@npm//@types/node",
    ],
)